version: "3"

services:
  backend:
    container_name: "backend"
    restart: unless-stopped
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.dev
    command: ./start.sh
    volumes:
      - .:/app:delegated
    ports:
      - 8000:8000
    stdin_open: true
    tty: true
  postgres:
    container_name: postgres
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=todo
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pg_data:
